#!/bin/bash

#Reference command flight example

# Date
grep '^HFDTE' 553c6742.igc | cut -c 6-

# Pilot name
grep '^HFPLT' 553c6742.igc | cut -d : -f 2

# Plane type
grep '^HFGIDGLIDERID' 553c6742.igc | cut -d : -f 2

# Start time
grep '^B' 553c6742.igc | cut -c 2-7 | head -n 1

# End time
grep '^B' 553c6742.igc | cut -c 2-7 | tail -n 1

# Highest GPS altitude
grep '^B' 553c6742.igc | cut -c 31-35 | sort | tail -n 1

# All pilots
grep ^HFPLT *.igc | cut  -d : -f 3 | sort | uniq
